### ISSUE TITLE
WebserverError

### ISSUE THREAD

**Issue by thany** [bloudermilk/reddit_image_downloader#6]
When running it like this:

```
reddit_image_downloader -r=Archaeology
```

I get this error:

```
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/snoo-0.1.2/lib/snoo/utilities.rb:20:in `get': 404 (Snoo::WebserverError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/snoo-0.1.2/lib/snoo/listings.rb:43:in `get_listing'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/lib/reddit_image_downloader/processor.rb:45:in `block in listings'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/lib/reddit_image_downloader/processor.rb:44:in `map'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/lib/reddit_image_downloader/processor.rb:44:in `listings'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/lib/reddit_image_downloader/processor.rb:8:in `process!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/lib/reddit_image_downloader/processor.rb:4:in `process!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/bin/reddit_image_downloader:10:in `<top (required)>'
        from C:/Ruby22-x64/bin/reddit_image_downloader:22:in `load'
        from C:/Ruby22-x64/bin/reddit_image_downloader:22:in `<main>'
```

That's on Ruby 2.2.3, Gem 2.6.6, Windows 10. All gems are up to date.

However, when I call it like this:

```
reddit_image_downloader --subreddits=Archaeology
```

This will be the result:

```
C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:858:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mechanize-2.7.4/lib/mechanize/http/agent.rb:267:in `fetch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mechanize-2.7.4/lib/mechanize.rb:464:in `get'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/lib/reddit_image_downloader/processor.rb:9:in `block in process!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/lib/reddit_image_downloader/processor.rb:8:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/lib/reddit_image_downloader/processor.rb:8:in `process!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/lib/reddit_image_downloader/processor.rb:4:in `process!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/reddit_image_downloader-0.1.1/bin/reddit_image_downloader:10:in `<top (required)>'
        from C:/Ruby22-x64/bin/reddit_image_downloader:22:in `load'
        from C:/Ruby22-x64/bin/reddit_image_downloader:22:in `<main>'
```

**Comment by thany** [comment]
I found another reddit (which is nsfw, so I shouldn't mention it here) which works, but only downloads five pictures, even though the subreddit has hundreds if not thousands.

**Comment by bloudermilk** [comment]
Hi @thany thanks for reporting. Unfortunately I'm no longer supporting this project and can't offer any quick solutions based on the errors you shared. Please do let me know if you end up solving this problem 😁
